services:
  - type: web
    name: point-dos-malokas
    env: node
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: TZ
        value: America/Sao_Paulo
      - key: JWT_SECRET
        generateValue: true
      - key: PIX_KEY
        value: "+5511961962855"
      - key: PIX_MERCHANT_NAME
        value: Vanice de Souza Santos
      - key: PIX_MERCHANT_CITY
        value: Sao Paulo
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: VAPID_PUBLIC_KEY
        value: BCcVZeMDPQHidvNvor5UEqchWoSMeBLikkV4OSF7XWwqvAM82YercuuWNhYctOk4sRzrJ4oJfonQtgOJt-LoYc8
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        sync: false
